# Generated by Django 5.1.11 on 2026-03-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pharmaceutical_tablet", "Pharmaceutical Tablet"),
                            ("artesunate_injection", "Artesunate Injection"),
                            ("surgical_instruments", "Surgical Instruments"),
                            ("ibuprofen", "Ibuprofen"),
                            ("desi_chicks", "Desi Chicks"),
                            ("optical_instruments", "Optical Instruments"),
                            ("amoxicillin_syrup", "Amoxicillin Syrup"),
                            ("ceftriaxone", "Ceftriaxone"),
                            ("pantoprazole", "Pantoprazole"),
                        ],
                        max_length=50,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("strength", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mrp_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("reorder_level", models.IntegerField(default=10)),
                ("min_order_quantity", models.IntegerField(default=1)),
                ("max_order_quantity", models.IntegerField(default=100)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("composition", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("shelf_life", models.IntegerField(blank=True, null=True)),
                (
                    "warehouse_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chennai", "Chennai Main"),
                            ("mumbai", "Mumbai Branch"),
                            ("delhi", "Delhi Branch"),
                            ("bangalore", "Bangalore Branch"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "storage_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("room_temperature", "Room Temperature"),
                            ("refrigerated", "Refrigerated (2-8°C)"),
                            ("frozen", "Frozen (-18°C or below)"),
                            ("cool_dry", "Cool & Dry"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
