# Generated by Django 5.1.11 on 2026-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
